[tool.black]
line-length = 88
target-version = ["py311", "py312", "py313"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]